openapi: 3.0.1
info:
  title: Recog Java
  description: Recog Java
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/recog-java
  x-cortex-tag: recog-java
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: vm-asset-assessment
  x-cortex-groups:
   - target:on-premise
   - strategy:on-prem
   - criticality:critical
   - exposure:opensource
